services:
  - type: web
    name: chatmeet
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chat_project.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: chatmeet-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOST
        value: .onrender.com

  - type: redis
    name: chatmeet-redis
    ipAllowList: []
    plan: free

databases:
  - name: chatmeet-db
    databaseName: chatmeet
    user: chatmeet
    plan: free
