services:
  - type: web
    name: chatmeet
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: daphne chat_project.asgi:application --port $PORT --bind 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: chatmeet-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: chatmeet-wn9f.onrender.com
      - key: WEB_CONCURRENCY
        value: 4
      - key: REDIS_URL
        fromService:
          name: chatmeet-redis
          type: redis
          property: connectionString

  - type: redis
    name: chatmeet-redis
    ipAllowList: []
    plan: free

databases:
  - name: chatmeet-db
    databaseName: chatmeet
    user: chatmeet
    plan: free
