# Generated by Django 3.2.19 on 2025-01-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestuser',
            options={'ordering': ['-last_activity']},
        ),
        migrations.RemoveField(
            model_name='guestuser',
            name='about',
        ),
        migrations.RemoveField(
            model_name='guestuser',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='guestuser',
            name='preferences',
        ),
        migrations.AddField(
            model_name='guestuser',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
